### ISSUE TITLE
"verification" group instead of "report"

### ISSUE THREAD

**Issue by Vampire** [szpak/gradle-pitest-plugin#136]
I just start using pitest and I wondered whether the task wouldn't better fit in the `verification` group where also `check`, `test`, `jacocoTestReport` and similar are in.
At least that is where I searched it until i found it in `report`.

**Comment by szpak** [comment]
Sounds reasonably. I started this project around Gradle 1.0 and I'm not sure if the `verification` group existed then :). Would you like to provide a pull request?

**Comment by Vampire** [comment]
There you have it :-)

**Comment by szpak** [comment]
Available in 1.4.5.
