### ISSUE TITLE
@Option to select tests for PitestTask

### ISSUE THREAD

**Issue by Vampire** [szpak/gradle-pitest-plugin#143]
Since Gradle 4.6 you can add custom command-line flags for tasks using the @Option annotation.
It would be nice if the PitestTask had such an option like `--tests` for the `Test` task, to easily select the tests to run to not have to always run all tests when you are working on something specific.

**Comment by szpak** [comment]
Last of support for List/SetProperty (explained in #139) makes the implemention of that harder (more "hacky").

**Comment by szpak** [comment]
I implemented it as:
```
gw pitests --targetTests com.example.tests.*
```
which overrides `targetTests` defined in the project configuration. Does it satisfy your needed?

**Comment by Vampire** [comment]
Well, I called it `--tests` to have it consistent with the default Gradle `Test` task, but `--targetTests` will probably also do, as long as it works as intended. :-)

**Comment by Vampire** [comment]
Hm, while thinking about it, for my use-case it would actually be more helpful to be able to (also) set `targetClasses`, can you do the same for that one please? :-)
