### ISSUE TITLE
Unable to debug PITTest in intellij

### ISSUE THREAD

**Issue by amitchidrewar1301** [szpak/gradle-pitest-plugin#163]
Hi Team,

I have added Pittest configuration in build.gradle configuration.

pitest {
    mainProcessJvmArgs = ['-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005']
}

Also i am running below command to start the debugging
./gradlew pitest -Dorg.gradle.debug=true

but I am getting
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

I wanted to debug the test case on intellij. Please let me know what are the steps to debug the pittest test cases.

**Comment by amitchidrewar1301** [comment]
So underline issue is we are getting -

Exception in thread "main" org.pitest.help.PitHelpError: **All tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.**
See http://pitest.org for more details.
        at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:109)

So as it clearly mentions our **mutation test cases are failing**. And Hence I wanted to debug the test cases to fix.  **Can you please share the steps do that on **Intellj****?,

Apologies to ask basic questions as Novice to this plugin.

**Comment by szpak** [comment]
Please enable verbose logging in PIT. Then you will see which tests were failing. It should be easier than debugging.

```
pitest {
    ...
    verbose = true
}
```

**Comment by szpak** [comment]
@amitchidrewar1301 Have you been successful in finding the tests that are failing?
