### ISSUE TITLE
Noisy logging "Adding dependency"

### ISSUE THREAD

**Issue by embee1981** [szpak/gradle-pitest-plugin#182]
Logging at
https://github.com/szpak/gradle-pitest-plugin/blob/0da91e16a09b2882e0b13a2d2550c25096e6e9c0/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L225

should be at info level when using the new style of junit5PluginVersion

v1.4.7 of plugin

**Comment by szpak** [comment]
Yes, it should be. I copied `log.warn` from https://github.com/szpak/gradle-pitest-plugin/blob/0da91e16a09b2882e0b13a2d2550c25096e6e9c0/src/main/groovy/info/solidsoft/gradle/pitest/PitestPlugin.groovy#L221 where `warn` is justified. Thanks for report that, I will fix by the next version.

In the meantime, as a workaround you can add JUnit 5 dependency in the old way ;-).
