### ISSUE TITLE
Remove any references to version 1.3 and anything older from README

### ISSUE THREAD

**Issue by pkubowicz** [szpak/gradle-pitest-plugin#215]
Currently reading the README feels like reading a history book from school. You want to learn who Pinochet was, but you need to read about Mesopotamia and Middle Ages.

As a new user, I don't care how problems were solved 2 minor versions ago. I don't want to filter through workarounds for problems present in old versions but not appearing now.

Version 1.4.0 appeared 1.5 year ago. I can agree that information about 1.4.x may be useful for some users having problems upgrading, so it may make sense keeping it. Anything older than it has to away - if someone is stuck 2 years in past, they should pay the price of such a technical debt. Let them look for the README of the Git tag they use - it does not change.

There are multiple references to plugin version 1.1.4, which is even older than 1.5 year old. It's kind of ridiculous.

---

If you agree but don't have time, I can clean up the README and open a pull request - please comment.

**Comment by szpak** [comment]
Sounds good. I would be happy accepting your PR!
