### ISSUE TITLE
Could not find method pitest() for arguments  on root project 'Mutation Testing Example' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by shivaburugu** [szpak/gradle-pitest-plugin#220]
Created a sample android application and getting couldn't find method pitest() with grade 4.0.0 and gradle wrapper 6.1.1, sample project can be found here 

https://github.com/shivaburugu/pitest

complete error 
Could not find method pitest() for arguments [build_6nwufs51r2yx8z6nu28e9e7e9$_run_closure1@52bf546d] on root project 'Mutation Testing Example' of type org.gradle.api.Project.

**Comment by szpak** [comment]
The plugin in this repo is for regular JVM applications. For Android application see [this fork](https://github.com/koral--/gradle-pitest-plugin/).
