### ISSUE TITLE
Unable to resolve pitest-command-line - no repositories defined

### ISSUE THREAD

**Issue by Redattack34** [szpak/gradle-pitest-plugin#23]
The gradle-pitest-plugin fails when used in a subproject of a multi-project build unless the root project has mavenCentral() defined as a buildscript repository - even if the subproject itself has mavenCentral() defined as a buildscript repository. Depending on the version of Gradle and the circumstances of the build scripts, it may either give a simple "could not resolve pitest-command-line" error, or it may include a message about how there are no repositories defined.

In case my description isn't clear enough, I set up a basic gradle project to demonstrate (https://dl.dropboxusercontent.com/u/3202601/Gradle-Pitest-Example.zip). Running 'gradle pitest' in the pitest-plugin-test subproject will fail to resolve the dependency. If you add "buildscript.repositories.mavenCentral()" to the buildscript in the root project, it will resolve normally.

This is confusing and counter-intuitive - if a user is not aware of this requirement, it appears as though appropriate repositories are defined. If this is intentional, it should at least be documented.

While I was trying to figure it out, I tried older versions of this plugin and found that version 0.33.0 works as expected, but version 1.0.0 and all later versions do not.

**Comment by szpak** [comment]
Yes, there were changes in 1.0.0 with configuration, but I cannot recall why exactly I moved it to root package. Even more currently I see it as a better place to use. Unfortunately it would break existing builds (for people who put plugin dependency only in root project - not in allprojects), so I will add an entry to FAQ explaining the error message.

Thanks your report.

**Comment by iirekm** [comment]
The  "could not resolve pitest-command-line" error message is misleading, it took me a few hours to figure out that the `buildscript {...}` part should be moved to top-level project. Wouldn't it be better to provide a message like 'please move ... to root project' or (best) get rid of this limitation. FAQ entry is too little, most programming (including me) read documentation rarely :-)
