### ISSUE TITLE
Gradle plugin 1.1.4 to PIT 1.1.4 compatibility?

### ISSUE THREAD

**Issue by nskmda** [szpak/gradle-pitest-plugin#26]
When trying PIT with 
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.4'
    }
}
```
in the parent __build.gradle__ and 
```groovy
apply plugin: "info.solidsoft.pitest"

pitest {
    targetClasses = ['com.promo.*']
    pitestVersion = "1.1.4"
    threads = 4
    outputFormats = ['XML', 'HTML']
    excludedMethods = ['equals', 'hashCode']
}
```

in the module __build.gradle__

I get the following:

```
Exception in thread "main" org.pitest.util.PitError: Unable to load class content for org.pitest.boot.HotSwapAgent

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 328
Input -> 
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.classBytes(JarCreatingJarFinder.java:124)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.addClass(JarCreatingJarFinder.java:113)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJarFromClassPathResources(JarCreatingJarFinder.java:98)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJar(JarCreatingJarFinder.java:74)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.getJarLocation(JarCreatingJarFinder.java:63)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:70)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:72)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
```

When falling back to the 

```gradle
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.2'
    }
}
```

in the parent __build.gradle__ the test run goes through fine.

Is it a compatibility issue or what?

**Comment by szpak** [comment]
Thanks for your report. I would rather suspect [a change](https://github.com/szpak/gradle-pitest-plugin/commit/288a6503ef6abf9e4bb3f410042f803c8488b5c8) which moved PIT and its runtime dependencies to launch classpath (rather that additional classPath). Nevertheless I have functional tests with multi-module project and they work fine.

1. Could you check my hypothesis by using gradle-pitest-plugin 1.1.4 and pitestVersion 1.1.3 (it should fail with the same error)?
2. Could you paste (or send on email) a plugin output when run with `--info`? Especially I am interested in run parameters pass to PIT (like classpath).

Btw, is this an open source project which I could build locally?

**Comment by nskmda** [comment]
Sorry for not replying promptly.

Yes, Gradle pit plugin 1.1.4 + PIT 1.1.3 gives the same error with this output:

```
Exception in thread "main" org.pitest.util.PitError: Unable to load class content for org.pitest.boot.HotSwapAgent

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 328
Input -> 
 1 : -Dfile.encoding=windows-1252
 2 : -Duser.country=US
 3 : -Duser.language=en
 4 : -Duser.variant
BootClassPathSupported : true

	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.classBytes(JarCreatingJarFinder.java:124)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.addClass(JarCreatingJarFinder.java:113)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJarFromClassPathResources(JarCreatingJarFinder.java:98)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.createJar(JarCreatingJarFinder.java:74)
	at org.pitest.mutationtest.tooling.JarCreatingJarFinder.getJarLocation(JarCreatingJarFinder.java:63)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:70)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:43)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:71)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:43)
```

Here is the output of running __gradle pitest__ with __--info__: https://gist.github.com/nskmda/4b9ce7ad3430885c707d

Unfortunately, mine is not an open source project. But I believe, the https://github.com/fbunau/game-of-life-mutation-test has the same issues. I just tested it with original plugin+pit version combination and then the 1.1.4+1.1.4 and it fails the same way my project does.

**Comment by mbruner** [comment]
I have same issue.
I've tried custom build of your plugin and following fix solved this issue. I changed
```
map['includeLaunchClasspath'] = false //code to analyse is passed via classPath
```
to
```
map['includeLaunchClasspath'] = true
```
Looks like it says to pitest to include `pitest-1.1.4.jar` and others to classpath when running tests.

**Comment by szpak** [comment]
@nskmda Your output looks ok. I've just tried build game-of-life-mutation-test with the plugin and PIT upgraded to 1.1.4 and it worked fine (with Gradle 2.3):
```
- Statistics
================================================================================
>> Generated 16 mutations Killed 15 (94%)
>> Ran 31 tests (1.94 tests per mutation)
```
Did you have to change anything else do break the build in game-of-life?

@mbruner Including launchClasspath reverts the change mentioned before which does not put PIT (and its dependencies like old JUnit or Hamcrest versions) together with your projects dependencies. It should be enough to put PIT only on launch classpath (and it seems to work on my machine :) ).
Btw, do you also run PIT on Windows?
Btw2, do you also have problem with running [game-of-life-mutation-test](https://github.com/fbunau/game-of-life-mutation-test) with PIT and the plugin set to 1.1.4?

**Comment by nskmda** [comment]
Well, I'm not sure right now (at home) which Gradle version we use (i personally prefer Maven).
I will check and let you know.
But I didn't change anything in the 'game of life' project except for the pitest plugin / PIT versions.
And yes, I run Windows at work.

**Comment by szpak** [comment]
@hcoles Do you have an idea what could be wrong? Run parameters (`-cp` and your `--classpath`) in [gist](https://gist.github.com/nskmda/4b9ce7ad3430885c707d) (line with "Starting process") look good for me and the same project work on my machine with both PIT and the plugin changed to 1.1.4. Should it be enough to put PIT jars only on run classpath?

**Comment by mbruner** [comment]
I run PIT on Windows.
I tried game-of-life-mutation-test:
1) Windows - failed
2) Mac OS - successful

**Comment by nskmda** [comment]
My Windows Gradle is 2.2. It fails.
My workmate just ran in on Fedora. Same Gradle 2.2.  1.1.4+1.1.4 goes through.
Something seems to be wrong with Windows.

**Comment by szpak** [comment]
Good news guys. I as able to trace down the [problem](https://github.com/hcoles/pitest/issues/179) in PIT code base and made [modifications](https://github.com/hcoles/pitest/pull/180) which fix it. Hopefully they will be included in the next version of PIT.

**Comment by szpak** [comment]
Btw, you can try latest pitest [snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/pitest/pitest/1.1.5-SNAPSHOT/) to verify that the problem was solved with my patch.

To use SNAPSHOT version it is required to add snapshot repository:
```
buildscript {
    repositories {
        mavenCentral()
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    }
    (...)
}
```

**Comment by nskmda** [comment]
Thanks a lot.
It's okay, take your time. We'll wait for the next version.

**Comment by szpak** [comment]
PIT 1.1.5 has been [released](https://github.com/hcoles/pitest/releases/tag/pitest-parent-1.1.5). It should be enough to set `pitestVersion` to `1.1.5` to restore compatibility with Windows.

Please reopen that issue in case of further problems.
