### ISSUE TITLE
Deprecate/remove maxMutationsPerClass

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#266]
It has been removed long time ago, but left in by accident and leftovers were effectively [removed](https://github.com/hcoles/pitest/pull/888) in 1.6.6.

`features = ["+CLASSLIMIT(limit[6])"]` can be used instead.

*Subject/message updated to the Henry's comment*

**Comment by hcoles** [comment]
Actually removed quite some time ago (before the 1.0.0 release I think) when the feature was re-implemented, but the parameter got left in by accident.
