### ISSUE TITLE
testPlugin parameter is automatically supplied

### ISSUE THREAD

**Issue by hcoles** [szpak/gradle-pitest-plugin#306]
Hi Marcin,

The testPlugin parameter hasn't done anything in pitest since 1.6.7, and the intention is to remove it from the codebase.

It looks as if the gradle plugin is passed a value for it even when it is not set by the user. If the parameter is fully removed from pitest, this results in an error.

The simplest solution seems to be to stop sending the parameter, thereby setting the minimum supported version of pitest to 1.6.7. As I think the default bundled version is 1.70, I can't imagine this would cause an issue for many users.

**Comment by szpak** [comment]
Hi Henry. Thanks for a reminder. I initially planned to deprecated it in 1.7.0 (#277), but postponed it to do not mix problems with JUnit Platform 1.8.0 with the aforementioned. It might be a good time to release 1.7.1. I could deprecate the parameter in the plugin (to print a warning) and at the same time stop passing it to PIT. I would also bump the minimal required version to 1.7.0 as your suggested.

Btw, do you plan to remove it in 1.8.0 or somehow earlier?

**Comment by hcoles** [comment]
I had planned to remove it in 1.7.5, but now you've pointed it out that clearly isn't appropriate as it's a breaking api change. So, yes, it will be in 1.8.0.

**Comment by szpak** [comment]
Implemented in 1.7.4. More details in  #277.
