### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by vanniktech** [szpak/gradle-pitest-plugin#31]
I was trying to add this one to an android project and Gradle fails.

```
./gradlew pitest
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':module'.
> The 'java' plugin has been applied, but it is not compatible with the Android plugins.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Are there any plans on supporting android?

**Comment by szpak** [comment]
It's the same issue as #24. Do you also use robolectric-gradle-plugin or something else?

**Comment by vanniktech** [comment]
You don't need that plugin anymore. At least it's no longer mandatory. Google guys have recently launched [Java Unit Tests for Android projects](http://tools.android.com/tech-docs/unit-testing-support), so that can be used. So you only need to include the dependency `testCompile 'org.robolectric:robolectric:3.0'`.

From the command line you can `./gradlew clean test` for executing the tests. The task itself is however named `test<Module+Flavor>UnitTest`

**Comment by szpak** [comment]
Thanks for the information. I suspect that it also uses JavaBasePlugin instead of JavaPlugin which is not very feasible to support both in the same code base. Nevertheless it is not hopeless, so I will probably give it a shot (one day). Votes from other Android developers willing to use PIT in their project could make that day sooner :).

**Comment by emartynov** [comment]
Also interested to try

**Comment by mdhornet90** [comment]
Definitely interested.

**Comment by gdaolewe** [comment]
Also interested, mutation testing is a great concept that issues like this have always kept me from using in any project.

**Comment by JosephYao** [comment]
Definitely interested.

**Comment by bnacey** [comment]
Very interested

**Comment by Endran** [comment]
Me as well!

**Comment by vanniktech** [comment]
@szpak what's the state of this, since the creation of this issue quite a few others are interested in this

**Comment by szpak** [comment]
Is [this](https://sites.google.com/a/android.com/tools/tech-docs/unit-testing-support) the only recommended way of testing that would be good to be supported?

**Comment by bnacey** [comment]
@szpak The document you linked appears to be very old. Look [here](https://developer.android.com/training/testing/start/index.html) for more up to date references about testing in Android

**Comment by xgouchet** [comment]
Really interested about this as well !

**Comment by szpak** [comment]
I cannot declare when I will be able to take a look at the possibility of implementation that. However, if someone provided a really small/minimal example of the Android application with a test which can be mutated I could use it as an acceptance test (that sunny day).
It would be good to make it possible to run unit tests from Travis, preferable without Android SDK downloaded and installed.

**Comment by emartynov** [comment]
Here is my pet project that has some test in it https://github.com/emartynov/android-template-project. It also runs no Travis.

I also tried to quickly make it working for android https://github.com/emartynov/gradle-pitest-plugin, but should spend more time on it. The problem is that Android plugin can not be used together with Java, but it is actually extending it. Another problem that sources sets are empty at moment plugin applications. And if I'm correct they will be available after evaluation

**Comment by szpak** [comment]
Yup. I had similar [observations](https://github.com/szpak/gradle-pitest-plugin/issues/24) and because of that I'm not if it will be possible/feasible to have just one plugin class for Java apps and Android apps. However, it was just a brief look.

Thanks @emartynov for the project.

**Comment by szpak** [comment]
Btw, @emartynov This project requires Android SDK which can be problematic (long running) to use on Travis. As I read the aforementioned [documentation](https://developer.android.com/training/testing/start/index.html) for unit testing:
> Local unit tests are tests that run on your local machine, without needing access to the Android framework or an Android device.
[This] page also does not mention Android SDK - just mocking Android dependencies.

Is it possible to run unit tests without Android SDK?

**Comment by mdhornet90** [comment]
I thought that the primary benefit of Robolectric was that it ran Android code on the JVM. If that's 100% the case, it should absolutely be possible.

**Comment by emartynov** [comment]
@szpak we treat Android SDK as JDK, which you have to download and install once. 
After your unit tests should be runnable offline as you expect

**Comment by koral--** [comment]
@emartynov was correct (https://github.com/szpak/gradle-pitest-plugin/issues/31#issuecomment-226225229) - required data is available after project evaluation.
Additionally it seems that pitest plugin must either apply android plugin (but it doesn't know which one - application, library or test) or be applied after android plugin (like eg. android-apt does).
Here is my try: https://github.com/koral--/gradle-pitest-plugin

There are some issues with tests using particular classes (eg. `org.robolectric.annotation.Config`) but simple examples (like those from functional tests) seems to work.

**Comment by Shyish** [comment]
Any updates on this? Would be really nice to have this working on Android.

**Comment by szpak** [comment]
You can use an Android for provided by @koral--  - https://github.com/koral--/gradle-pitest-plugin . It seems to work and As the changes there are quite heavy (and incompatible) I'm not very eager to backport them to a vanilla JVM version.

**Comment by FloKaemmerer** [comment]
@koral-- I tried using your plugin on an Android project, but I'm not able to get it to work.

I striped down my project to a simple example: [https://github.com/FloKaemmerer/PiProblem](https://github.com/FloKaemmerer/PiProblem)
Running the testsuit runs green, no matter if I'm using Androidstudio or gradle.

But when I try to use the pitest task, the test fails.

Any tips would be appreciated.

**Comment by Shyish** [comment]
@FloKaemmerer I have the same issue at the moment. I think we should translate this conversation to that repo so we don't spam this one, could you please create the issue there?

**Comment by FloKaemmerer** [comment]
@Shyish I would have opened an issue over there, but @koral-- didn't enable it :-/

**Comment by koral--** [comment]
Sorry, I just enabled isssues and created one: https://github.com/koral--/gradle-pitest-plugin/issues/1
I'll check that.

**Comment by vanniktech** [comment]
Since there seems to be a successor / fork I'll close this.

**Comment by szpak** [comment]
I would name is an Android version of that plugin. It cannot be used with the "normal" Java projects.

**Comment by vanniktech** [comment]
Oh okay got it. Maybe also mention the Android Version in the README.

**Comment by szpak** [comment]
The FAQ is in the README :)
