### ISSUE TITLE
Disabling generation of date subfolder

### ISSUE THREAD

**Issue by thatsIch** [szpak/gradle-pitest-plugin#32]
On every mutation run you need to "search" for the latest folder or write an regex parser to move the content of the latest folder into a general public folder. 

Is there some way to circumvent this behaviour easier?

**Comment by szpak** [comment]
`timestampedReports` parameter is something you need. Just add the following to the pitest configuration block in your build.gradle:
```
pitest {
    timestampedReports = false
}
```
See the [official documentation](http://pitest.org/quickstart/commandline/) for all available configuration parameters in PIT and the plugin [extension class](https://github.com/szpak/gradle-pitest-plugin/blob/master/src/main/groovy/info/solidsoft/gradle/pitest/PitestPluginExtension.groovy) to see how it is mapped to Gradle configuration.

**Comment by thatsIch** [comment]
ah thank you, I did not see it in your README.md so I was not aware that you can directly map the properties. Very convenient and smart implementation!
