### ISSUE TITLE
Task 'pitest' not found in root project

### ISSUE THREAD

**Issue by JustinLiang522** [szpak/gradle-pitest-plugin#332]
I tried to run `gradle pitest` for [this]( https://github.com/tasks/tasks) Android project. It showed an error that says **Task 'pitest' not found in root project**. I have added the pitest plugin in the `build.gradle.kts` as follows: 
```
plugins {
  id("info.solidsoft.pitest") version "1.9.0"
}
```

**Comment by szpak** [comment]
For just the others bumping into that issues, this plugin is [not compatible](https://github.com/szpak/gradle-pitest-plugin#can-i-use-gradle-pitest-plugin-with-my-android-application) with the Android projects (just pure Java projects) and the [Android fork](https://github.com/koral--/gradle-pitest-plugin/) should be used instead.
