### ISSUE TITLE
Add examples of using plugin with kotlin-dsl

### ISSUE THREAD

**Issue by mfvanek** [szpak/gradle-pitest-plugin#339]
I've faced with a lack of working examples for kotlin-dsl. For newbie Kotlin devs (like me) it's hard and sometimes unclear how to transform working groovy script to kotlin-dsl.

Usually in README.md there are some expandable blocks named 'with Kotlin DSL' where corresponding examples are located.  
For instance, see https://github.com/spotbugs/spotbugs-gradle-plugin or https://github.com/tbroyer/gradle-errorprone-plugin

Can we add documentation to README.md by analogy?

**Comment by mfvanek** [comment]
I'd like to make a PR if you consider this issue is worth attention

**Comment by szpak** [comment]
I'm stuck to Gradle as the Kotlin version (still) builds much longer and has some limitations. However, Gradle (still) promotes it, so it sound sensible to have also the Kotlin counterparts.

It would be great to have a PR with those changes. Please keep the Kotlin version collapsed.

**Comment by mfvanek** [comment]
I'm working on it. Still in progress
