### ISSUE TITLE
1.1.6 is not release to Gradle Central Plugin Repository

### ISSUE THREAD

**Issue by taichi** [szpak/gradle-pitest-plugin#34]
gradle-pitest-plugin 1.1.6 is not release to Gradle Central Plugin Repository.

https://plugins.gradle.org/plugin/info.solidsoft.pitest

please release it.

**Comment by szpak** [comment]
The plugin had been releasing to the Plugin Repository in the past, but some time ago Gradleware changed the way of uploading once again and now I don't know a way to publish artifact once and have them in both repositories (and Central is a MUST for me).
However I will take a look at it one day, to make it easier to use.

**Comment by taichi** [comment]
where is your published repository?

i think that here is your repository

* https://bintray.com/szpak/maven/info.solidsoft.gradle.pitest%3Agradle-pitest-plugin/view

but i can't see 1.1.6.

**Comment by szpak** [comment]
The plugin is being released to Maven Central, but every new version should be propagated to Bintray on the first request by some user. Have you tried it and failed from Gradle? If yes, let me know, maybe they (Bintray) changed something in that mechanism and I could dig it.

The easiest way is just to add `mavenCentral()` to your buildscript repositories.
https://search.maven.org/#artifactdetails|info.solidsoft.gradle.pitest|gradle-pitest-plugin|1.1.6|
(your can get that link by clicking on a version badge in the README file)

**Comment by taichi** [comment]
thanks for your recommendation. i wrote below.

```
buildscript {
	repositories.mavenCentral()
	dependencies {
		classpath "info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.1.6"
	}
}

apply plugin: "java"
apply plugin: "info.solidsoft.pitest"

sourceCompatibility = targetCompatibility = 1.8

tasks.withType(AbstractCompile)*.options*.encoding = "UTF-8"

pitest {
	pitestVersion = '1.1.7'
	targetClasses = ['example.*']
}

repositories.mavenCentral()
dependencies {
	testCompile 'junit:junit:4.+'
}
```

this script works fine.

**Comment by szpak** [comment]
Exactly. There is also an example at the beginning of the README file.

Btw, I created a separate issue - #35 - about the plugin portal if you would like to track the (possible) progress.

**Comment by szpak** [comment]
Btw2, as I predicted the 1.1.6 artifacts were lazy fetched from Maven Central by Bintray/jCenter when I tried to resolve them using only jcenter reposiotry in Gradle:
https://repo.jfrog.org/artifactory/libs-release-bintray/info/solidsoft/gradle/pitest/gradle-pitest-plugin/1.1.6/

**Comment by johnscancella** [comment]
Any chance of you releasing again to https://plugins.gradle.org/plugin/info.solidsoft.pitest?

**Comment by szpak** [comment]
There is. I've been [discussing](https://discuss.gradle.org/t/using-plugins-mechanism-with-maven-central/20111/6?u=marcin) it on their forum recently and I need to verify that it would be doable in my case.

**Comment by szpak** [comment]
Btw, @johnscancella I propose you to subscribe to #35 to get notification when it is eventually done.
