### ISSUE TITLE
Consider re-enable deployment to The Plugin Portal repository

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#35]
To make the plugin usage in end projects easier.

**Comment by thejohnfreeman** [comment]
Anything I can do to help with this?

**Comment by szpak** [comment]
Yes, you can :).

My vision/requirements to that process is/are:
 - artifacts are built, signed, published and promoted to Maven Central (aka The Central Repository) using already implemented mechanisms
 - the same artifacts (**without** rebuilding) are published to The Plugin Portal - probably using their closed-source [Plugin Publishing Plugin](https://plugins.gradle.org/docs/publish-plugin) by calling an another task (possibly as a separate Gradle execution). According to [that thread](https://discuss.gradle.org/t/using-plugins-mechanism-with-maven-central/20111/6?u=marcin) it should be possible)

I plan to work on it one sunny day, but I would gladly accept a contribution :).

**Comment by thejohnfreeman** [comment]
Great, I'll take a look!

**Comment by szpak** [comment]
Thanks to @thejohnfreeman (#55) starting with version 1.1.11 the plugin is again available via the Plugin Portal.
