### ISSUE TITLE
Compatibility with JUnit 5.10.0 is broken

### ISSUE THREAD

**Issue by rahulsom** [szpak/gradle-pitest-plugin#352]
I've created a test repo [here](https://github.com/rahulsom/pitest-junit-compat). Also attached [pitest-junit-compat.zip](https://github.com/szpak/gradle-pitest-plugin/files/12517120/pitest-junit-compat.zip)

You can run it with default versions and it works. [Gradle Build Scan](https://gradle.com/s/2cemwjn6ha6oq)

```shell
./gradlew pitest
```

It uses these versions

```
junitVersion=5.9.3
piTestJUnitVersion=1.0.0
piTestPluginVersion=1.9.11
piTestVersion=1.14.4
```

If you run it with junit 5.10.0, it fails. [Gradle Build Scan](https://gradle.com/s/jec2qcewxfuhm)

```shell
./gradlew pitest -PjunitVersion=5.10.0
```

**Comment by szpak** [comment]
After a quick look at the build scan:
> Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally! (UNKNOWN_ERROR)	

it might be the same as in #340 (but there with the verbose logging). Please add:

```
testRuntimeOnly("org.junit.platform:junit-platform-launcher") {
    because("required for pitest - https://github.com/szpak/gradle-pitest-plugin/issues/337")
}
```

**Comment by rahulsom** [comment]
Awesome. That fixes it. Thanks!

**Comment by szpak** [comment]
@rahulsom I created a draft PR using the latest SNAPSHOT version - https://github.com/rahulsom/pitest-junit-compat/pull/2 . Please test it in your real project, if you can, as there might be some corner cases.

**Comment by rahulsom** [comment]
Validated against the real project.
That works perfectly. Thanks!
