### ISSUE TITLE
Update for pitest 1.1.7

### ISSUE THREAD

**Issue by oneiros-de** [szpak/gradle-pitest-plugin#36]
pitest 1.1.7 is out: https://github.com/hcoles/pitest/releases/tag/pitest-parent-1.1.7

**Comment by szpak** [comment]
I can change it in master, but I don't think it is worth to release the new plugin version without any other change.

I created a mechanism to allow developers to specify (override) default PIT version with just:
```
pitest {
    pitestVersion = "1.1.7"
}

**Comment by oneiros-de** [comment]
Yes. :-)
