### ISSUE TITLE
Task 'pitest' not found in root project (Running pitest with Gradle 8.7) 

### ISSUE THREAD

**Issue by Bhumika2005** [szpak/gradle-pitest-plugin#361]
#In demo project, I have added pitest plugin in **libs.versions.toml** as below:
```
[versions]
....
kotlin = "1.9.0"
pitest = "1.15.0"

[libraries]
....

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
pitest = {id = "info.solidsoft.pitest", version.ref = "pitest"}
```

#Then added plugin in app build.gradle => **build.gradle.kts(:app)**
```
plugins {
alias(libs.plugins.androidApplication)
alias(libs.plugins.jetbrainsKotlinAndroid)
alias(libs.plugins.pitest)
}
```

build successful but ./gradlew pitest didn't work and getting error as below ::
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'pitest' not found in root project 'TestPitest' and its subprojects. Some candidates are: 'test'.
```

Then I found this [issue link](https://github.com/szpak/gradle-pitest-plugin/issues/358) and tried the same way

#Added dependency in app build.gradle.kts along with above change
```
dependencies {
    ....
 testImplementation(libs.junit)
androidTestImplementation(libs.androidx.junit)
androidTestImplementation(libs.androidx.espresso.core)
pitest("org.pitest:pitest-testng-plugin:1.0.0")
}
```

still same error message - "Task 'pitest' not found in root project 'TestPitest' and its subprojects. Some candidates are: 'test' "

Also added plugin / buildscript dependencies in root project build.gradle but nothing works.

Getting same error message everytime.

**Comment by szpak** [comment]
Please reformat you question to make the code readable:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
