### ISSUE TITLE
Incompatibility with new Kotlin versions

### ISSUE THREAD

**Issue by ivanvillarfreire** [szpak/gradle-pitest-plugin#362]
Good morning.

First of all, I want to sincerely appreciate the good work it's being done here over the years. 

I want to comment here what it seems to be some kind of incompatibility with at least the following versions:

```
------------------------------------------------------------
Gradle 8.6
------------------------------------------------------------

Build time:   2024-02-02 16:47:16 UTC
Revision:     d55c486870a0dc6f6278f53d21381396d0741c6e

Kotlin:       1.9.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.7 (Homebrew 17.0.7+0)
OS:           Mac OS X 13.0 aarch64
```

The problem in fact is pretty simple to see, on a build.gradle.kts file, if you include this section:

```
  packaging {
      resources.excludes.add("META-INF/{AL2.0,LGPL2.1}")
      resources.excludes.add("META-INF/LICENSE.md")
      resources.excludes.add("META-INF/LICENSE-notice.md")
  }
```

The gradle sync fails already with the errors:

```
applicationandroid/build.gradle.kts:139:5: Unresolved reference: packaging
```

```
applicationandroid/build.gradle.kts:140:19: Unresolved reference: excludes
```

The feeling I get, but I could be totally wrong, is that internally Pitest does some kind of packaging too but there is some new way to call that function and Pitest is not able to do it right.

The "good thing" is that if we comment the packaging section, it works just fine:

<img width="989" alt="image" src="https://github.com/szpak/gradle-pitest-plugin/assets/67439218/371f0e46-5e8e-4521-8916-ed6ba5d6b7ae">

And a `./gradlew pitest`:

<img width="1020" alt="image" src="https://github.com/szpak/gradle-pitest-plugin/assets/67439218/f3330b17-6b13-41f8-8e0f-3bbc95baf68e">

**Comment by szpak** [comment]
It seems to be the Android project. Please use an Android fork of this plugin: https://github.com/koral--/gradle-pitest-plugin/

**Comment by szpak** [comment]
> First of all, I want to sincerely appreciate the good work it's being done here over the years.

And thank you for the kind words!
