### ISSUE TITLE
Plugin does not support scala code

### ISSUE THREAD

**Issue by sinwe** [szpak/gradle-pitest-plugin#37]
Ran this plugin against `scala` code with `scalaTest` and it'll give 0% for line coverage and mutation coverage

**Comment by szpak** [comment]
I've never tried that combination. I assume that you try to test Java production code with tests written in Scala(Test). If yes could you provide a small project that reproduces that behavior?

**Comment by sinwe** [comment]
No, both production and test code are written in scala

**Comment by szpak** [comment]
Unfortunately PIT itself doesn't support mutation of production code written in Java. You can subscribe to get notification when/if http://www.faultseed.com/ is ready (the enhanced version of mutation testing engine with planned Scala and Groovy support).

Btw, in case you had also some production Java code tested with ScalaTest (what is very popular in Groovy and Spock) do not hesitate to provide a small example to test/verify if Gradle plugin supports it.
