### ISSUE TITLE
Control for timestamped reports

### ISSUE THREAD

**Issue by cverges-medallia** [szpak/gradle-pitest-plugin#38]
Currently, all reports output by the pitest plugin go into a timestamped directory under reportDir.  The [Maven](http://pitest.org/quickstart/maven/) plugin has an option `timestampedReports` that allows for control of this mechanism to better allow for automation around these reports.  This is a feature request asking to port `timestampedReports` to the Gradle plugin.

**Comment by cverges-medallia** [comment]
I just saw that #32 addresses this.  Perhaps this is actually a request to update the documentation to cover this more clearly?

**Comment by szpak** [comment]
Closing as there is a dedicated FAQ section and in addition that property is mentioned in the sample project configuration in README.

Feel free to provide a PR if you would need anything else related to that topic.
