### ISSUE TITLE
Update default PIT version due to crashes in 1.1.6

### ISSUE THREAD

**Issue by lukkezeh** [szpak/gradle-pitest-plugin#39]
When using version 1.1.6 of the gradle pitest plugin, pit will crash. This is most likely caused by the pit version used in the gradle pitest plugin. There is a known issue reported on version 1.1.6 of pit. Simply changing the version to 1.1.9 solved the issue for me. I don't know if there are any side effects when this is done.

**Comment by szpak** [comment]
Usually there should not be any side effects. Only not backward compatible changes are problematic. And of course there is no support to newly created PIT switches. The releases of gradle-pitest-plugin are not strictly synchronized with PIT releases. Usually the new features in PIT or internal changes in the plugin triggers the new release.

There is an entry about that topic in FAQ:
> 6. How can I change PIT version from default to just released the newest one?

I've just extended it to encourage people to report detected issues when the latest plugin version doesn't work correctly with newer PIT versions, but from your message I conclude that everything is ok in your case. Right?

**Comment by lukkezeh** [comment]
The standard version used by the plugin is 1.1.6. This version has a bug and therefore shouldn't be used.
The standard configuration is now incorrect and should be changed to a stable release for example 1.1.9.

The workaround described in the FAQ works but new users won't like to read the FAQ. Instead, they want a working plugin which works out of the box.

**Comment by szpak** [comment]
Ok, I think I understand your intentions now. Would the issue summary "PIT in default version (1.1.6) crashes" or "Update default PIT version due to crashes in 1.1.6" be more suitable?

**Comment by lukkezeh** [comment]
Yes.

**Comment by szpak** [comment]
I've changed the summary. Before the new release I will have to take a look at the recent changes in PIT as AFAIR there were some new features which could be supported in the plugin. Thanks for your report.
