### ISSUE TITLE
Need to upgrade to latest version of pitest:1.1.8

### ISSUE THREAD

**Issue by jpsw** [szpak/gradle-pitest-plugin#40]
We are hitting an issue that **gradle pitest** seems to hang forever after invoking the junit tests...

Googling a bit, I suspect it is this issue that was present in **pitest:1.1.6** 
and then fixed in version **1.1.7+** :

     https://github.com/hcoles/pitest/issues/231

But I find no **gradle-pitest-plugin** after **1.1.6** and I suspect that it's still using **pitest:1.1.6**, correct?

If so, are you planning to upgrade the gradle-plugin to the latest pitest-version?

Or is it possible, somehow, to have the **plugin-version:1.1.6** 
use the latest **pitest:1.1.8** ?

**Comment by szpak** [comment]
Yes, see #36 or FAQ in README.

In addition the new plugin version is planned in the foreseeable feature: #39.

**Comment by jpsw** [comment]
Aah, that helped! 
It works now, thank you! :)
