### ISSUE TITLE
Suggestion: Clarify how to make pitest depending on build

### ISSUE THREAD

**Issue by tomasbjerre** [szpak/gradle-pitest-plugin#43]
I was having a bit of a problem when trying to make build depend on pitest. Like this:
```
build.dependsOn pitest
```
It has to be done like this:
```
build.dependsOn "pitest"
```

Because the `pitest` task has the same name as the configuration.

This is just a suggestion to mention that in the README.md. Or just close the issue if you dont think its important.

**Comment by szpak** [comment]
You are right. I also encountered this problem once working with some other plugin. Thanks for your suggestion.

**Comment by szpak** [comment]
Btw, feel free to make a PR in a form which in your opinion will be meaningful for others.
