### ISSUE TITLE
Make dependency exclusion on classpath configurable

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#53]
Currently some kinds of dependencies (namely `*.pom`, `*.so`, `*.dll`, `*.dylib` as of 1.1.11) are filtered to not to fail during PIT execution (#52). That list could be made configurable if needed.

As there are some implementation issues to handle it in a flexible way please comment here if you need it in your project.

**Comment by mdietz198** [comment]
Hi, I'm running into this with *.xml files. It would be great to be able to specify extensions.

**Comment by szpak** [comment]
I abandon the idea to use regexps in favor of a list of extensions. In 1.2.4 (which is just being released on Travis) it is possible to add extra extensions to filter with:
```
pitest {
    ...
    fileExtensionsToFilter += ['xml', 'orbit']
}
```

Do not hesitate to comment here if you encounter any filtering related issue with the new version.

**Comment by mdietz198** [comment]
Thank you! I will give this a try as soon as I can!
