### ISSUE TITLE
classPathFile should not use exposed in configuration

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#56]
The Gradle plugin itself doesn't provide a direct way to specify a `classpath` passed to PIT - it is based on the project configuration. Due to an oversight  `classPathFile` has been exposed directly in the plugin configuration. It should be enough to have a `useClassPathFile` boolean configuration switch to pass a classpath to PIT using an automatically generated file instead of a `classpath` command line parameter.

**Comment by szpak** [comment]
Available in 1.2.2 - `useClasspathFile = true` has to be added to the plugin configuration.

**Comment by szpak** [comment]
I'm glad you finally found it :).

However, in the README file there is:
```
 - useClasspathFile - enables passing additional classpath as a file content
 (useful for Windows users with lots of classpath elements, disabled by default - since 1.2.2)
```
Nevertheless, feel free to provide a PR with improvements :).

**Comment by ninjubohra** [comment]
You think I would read the **entire** documentation before announcing my ignorance to the whole world 😢 
Thanks for a great plugin!
