### ISSUE TITLE
Consider pitest task cacheability

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#67]
If sensible mark task with [`@CacheableTask`](https://docs.gradle.org/4.1/javadoc/org/gradle/api/tasks/CacheableTask.html). It would be especially useful with Gradle Build cache introduced in Gradle 4.

Potential issues. That annotation has been added in Gradle 3.0. Check Gradle 2 compatibility in runtime.

**Comment by C-Otto** [comment]
I'd say Gradle4/3/2 support isn't necessary nowadays.

**Comment by szpak** [comment]
Nevertheless the cacheability is still trendy :-D.

@C-Otto Maybe you would like to take a look at the implementation options and eventually provide a PR? :-)

**Comment by SimY4** [comment]
@szpak isn't adding an annotation not binary breaking? I mean, whether you have annotation in your classpath or not doesn't stop classes from loading. So, if you run a version of Gradle with APIs where this annotation is present - it will be taken in effect, and if not - it'll work as it works today.

**Comment by szpak** [comment]
I believe that there were some [other requirements](https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details) for cacheability to be effective, however, as the project migrated to the property-based task parameters it might be fulfilled automatically. Still, there would need to be written a functional test confirming that in fact caching holds.

**Comment by davidburstrom** [comment]
I've been using

```
tasks.named<PitestTask>("pitest").configure {
  outputs.cacheIf { true }
}
```

since December 2019 and have yet to see any issues related to caching. My thinking is that it's pretty safe to turn it on, with a functional test, and deal with any subsequent issues as regular bugs.

**Comment by szpak** [comment]
Thanks for your comment. The inputs/ooutputs migration to  the Property-based replacement could do the trick. Would you like to add a functional test confirming that the second execution is cached?

**Comment by davidburstrom** [comment]
Done!
