### ISSUE TITLE
Support for testPlugin parameter

### ISSUE THREAD

**Issue by hcoles** [szpak/gradle-pitest-plugin#76]
Auto detection of test plugins was largely removed in pitest 1.3.0 and replaced with an explicit testPlugin parameter by this PR

https://github.com/hcoles/pitest/pull/429

Support for this parameter is required to use pitest 1.3.0 with junit5 or testng via gradle.

**Comment by christophsturm** [comment]
here's a demo project if that helps: https://github.com/christophsturm/pitest-gradle-it

**Comment by christophsturm** [comment]
do you want a pr for this?

**Comment by christophsturm** [comment]
PR: https://github.com/szpak/gradle-pitest-plugin/pull/77

**Comment by szpak** [comment]
Available in 1.3.0.
