### ISSUE TITLE
Evaluate Java 10 support

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#81]
Java 10 RC1 has been [released](mail.openjdk.java.net/pipermail/jdk-dev/2018-February/000742.html).

**Comment by szpak** [comment]
PIT 1.4.0 and Gradle 4.7 supports Java 10. Travis build has been added in master. Will be included in the next 1.4.x release.

**Comment by ysabri** [comment]
Hi, when is this release going to be available?

**Comment by szpak** [comment]
When all the tasks for this [milestone](https://github.com/szpak/gradle-pitest-plugin/milestone/16) will be implemented.

Btw, you should be able to use Java 11 with the current version of gradle-pitest-plugin with PIT 1.4.3 configured. If you encounter any Java 9+ related issues in my Gradle plugin itself, please let me know (preferably by reporting a separate issue).

**Comment by ysabri** [comment]
Yes I actually did encounter an issue using Java 10 and Gradle 4.9.

I'm more than happy to open an issue, just tell me what you want me to include in it.

**Comment by szpak** [comment]
A standard set of answers should be enough to get started.
 - What did you do? 
 - What did you get?
 - What did you expect to get?

A fragment of the output is definitely a thing to include. Your configuration, CI server log and your project link (if it is publicly available), if appropriate.
