### ISSUE TITLE
Check Java 11 support

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#86]
Once Gradle supports Java 11 and PIT [1.4.1](https://github.com/hcoles/pitest/pull/471) is released.

**Comment by szpak** [comment]
Smake tests work fine with Gradle 4.9 and PIT 1.4.1. The master branch is automatically tested with Java 8-11.

**Comment by ysabri** [comment]
Hi @szpak, what is the timeline for releasing this under milestone 1.4.0?

**Comment by szpak** [comment]
Firstly, I want to bring my other [plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/) back online after the Travis changes. Nevertheless, I wonder if you spotted any issue while working with gradle-pitest-plugin 1.3.0 and the PIT version set to 1.4.3 (with `pitestVersion = 1.4.3`)?

**Comment by szpak** [comment]
Anyway, I emphasized it in [FAQ](https://github.com/szpak/gradle-pitest-plugin#10-how-to-use-gradle-pitest-plugin-130-with-java-11).

**Comment by ysabri** [comment]
It just worked, thanks a lot, it was my fault for not reading the documentation.

**Comment by szpak** [comment]
You are not the first one, so it's not intuitive. I plan to release 1.4.3 with no new features, just with PIT 1.4.3 by default to make everyone live easier. Thanks for reporting your problem.
