### ISSUE TITLE
Test plugin not found when dependency is declared in sub module

### ISSUE THREAD

**Issue by hemeroc** [szpak/gradle-pitest-plugin#88]
Hi, I set up the structure of my project as follows:

```
root
├── sub1
└── sub2
```

PITest should only run in submodule 1 therefore the submodule 1 includes following configuration:
```
buildscript {
    repositories {
        mavenCentral()
    }
    configurations.maybeCreate('pitest')
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.3.0'
        pitest 'org.pitest:pitest-junit5-plugin:0.5'
    }
}

apply plugin: "info.solidsoft.pitest"

pitest {
    pitestVersion = "1.4.0"
    testPlugin = "junit5"
    verbose = true
}
```

Running `./gradlew pitest` or `./gradlew :sub1:pitest` results in following error Message:
```
4:16:19 PM PIT >> FINE : MINION : org.pitest.util.PitError: Could not load requested test plugin junit5
```
_(verbose output has to be activated to see this line!)_

It seems that the pitest plugin fails setup the correct classpath.
As soon as I add the `pitest 'org.pitest:pitest-junit5-plugin:0.5'` dependency to the `build.gradle` of the root project it works as expected.

I created the same issue in the `pitest/pitest-junit5-plugin` repository. But now I think this is more related to the general way the pitest gradle plugin resolves plugin dependencies. Sorry for the duplication.
https://github.com/pitest/pitest-junit5-plugin/issues/8

**Comment by szpak** [comment]
pitest-gradle-plugin could try to resolve some default plugins, but in general I think it is not the best idea as people could expect to have it supported for all the plugins (possibly provided by 3rd-party vendors). Nevertheless, it could be nice to have the error mentioning the missing plugin more exposed (and maybe suggesting in some way what should be added for in-house plugins - which is more tricky).

**Comment by hemeroc** [comment]
The problem in my opinion is not about automatic resolving of default plugins.
I think you should declare each plugin as dependency but why does it have to be a dependency of the root module instead of the submodule?

**Comment by szpak** [comment]
In that case this is related to #62.

**Comment by hemeroc** [comment]
To be honest I don't think that this two issues are related.
Declaring the pitest plugin itself in the submodule works totally fine.
It's just that you have to declare "plugins" (like the junit5 plugin) for the pitest gradle plugin in the root `build.gradle`.

**Comment by szpak** [comment]
It is. Currently the `pitest` configuration where the PIT itself and (optionally) the plugins is added is created in the root project. The repository in #62 has to be added to have the PIT jar resolved. It's shared across all the subpojects. Usually it's not a problem, but at least can be confusing.

**Comment by szpak** [comment]
@hemeroc There is a snapshot with the new SNAPSHOT version which may help in the aforementioned situation (assuming it is still valid for you).
