### ISSUE TITLE
How can I change the task classpath to add JUnit?

### ISSUE THREAD

**Issue by mdbergmann** [szpak/gradle-pitest-plugin#89]
Hello.
I have integrated the pitest plugin into by gradle script.
But when executing pitest always complains that it can't find JUnit in the classpath.

```
> Task :pitest FAILED
21:44:06 PIT >> INFO : Verbose logging is disabled. If you encounter an problem please enable it before reporting an issue.
21:44:06 PIT >> INFO : Sending 0 test classes to minion
21:44:06 PIT >> INFO : Sent tests to minion
21:44:06 PIT >> SEVERE : Error generating coverage. Please check that your classpath contains JUnit 4.6 or above.
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.
```

How can I modify the classpath?

**Comment by szpak** [comment]
It should be added by default. Do you have a multi-project build? May it be related to #88/#62? What JUnit version to you use (4/5)?

Can you share a link to that project?

**Comment by szpak** [comment]
Is the issue still valid? Can you provide more details on the problem?

**Comment by mdbergmann** [comment]
Can't share a link unfortunately.

I've followed the setup as outlined in #88.
```
buildscript {
    repositories {
        mavenCentral()
    }
    configurations.maybeCreate('pitest')
    dependencies {
        classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.3.0'
        pitest 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.3.0'
    }
}
```

And later, in 'subprojects'
```
    apply plugin: 'info.solidsoft.pitest'

    pitest {
        pitestVersion = "1.4.0"
        testPlugin = 'junit4'
        verbose = true
    }
```

When running `./gradlew pitest` I'm still getting:
`PIT >> FINE : MINION : org.pitest.util.PitError: Could not load requested test plugin junit4`

**Comment by szpak** [comment]
Please remove:
> pitest 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.3.0'
and
> testPlugin = 'junit4'

**Comment by mdbergmann** [comment]
That seemed to have worked. Thank you.
At least it could find junit4 now.
