### ISSUE TITLE
Support useClasspathJar (PIT 1.4.2)

### ISSUE THREAD

**Issue by szpak** [szpak/gradle-pitest-plugin#92]
It changes internal communications with minions in PIT to do not exceed the classpath length in large projects. Upstream PR: https://github.com/hcoles/pitest/pull/500/.

**Comment by davidburstromspotify** [comment]
Thank you for fixing this! We need this as classpaths have been outgrowing the minions for a while.

**Comment by davidburstromspotify** [comment]
Hi! Is there any chance this can be merged and released?

**Comment by szpak** [comment]
In fact it was merged and I "forgot" about that. I will try to release "soon".

**Comment by szpak** [comment]
1.4.6 should be available in Maven Central. Thanks for your reminder - as the releasing is automatized I could easily do it in September...

**Comment by davidburstromspotify** [comment]
Thank you, it worked like a charm! I'm very happy to say that we've been able to kill off our forks of the plugins (Android and Java).
