### ISSUE TITLE
additionalClasspath must be annotated with @Classpath

### ISSUE THREAD

**Issue by davidburstromspotify** [szpak/gradle-pitest-plugin#93]
additionalClasspath in PitestTask must be annotated with `@Classpath` instead of `@InputFiles`. Otherwise Gradle caching breaks, as there are often JAR files on the classpath that gets regenerated while cleaning a build. `@InputFiles` cares about the whole file hash, `@Classpath` only cares if the classes in the JARs have changed.

**Comment by szpak** [comment]
Sounds reasonable. Would you like to provide a PR?

Btw, probably it would be good to keep both `@InputFiles` and `@Classpath` on that field to keep the compatibility with older Gradle versions.

**Comment by davidburstromspotify** [comment]
I would be happy to provide a PR but unfortunately I'm hitting https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github as I've already forked the Android version.

**Comment by szpak** [comment]
Ok, I will do that. However, for a reference, it is not impossible to do it in GitHub. It should be enough (I haven't tested that particular case, but looking at the GH UI it should be enough) to add my repository as another remote repository (as `base` or `szpak`), fetch changes, create your own branch from my `szpak/master`, make changes and push it to your repo. Next, it is needed to click "create pull request" (in my or the Android repo) and switch "base fork" to mine, while leaving or setting your new branch from your fork/repo.

**Comment by davidburstromspotify** [comment]
You're technically correct, the best kind of correct :)

**Comment by szpak** [comment]
Fixed in master. It will be a part of the next release (which may take some time as I need to do some bigger changes before). Anyway it can be backported to the Groovy version earlier, if you convince Karol to do that :).

Thanks for the report.

**Comment by davidburstromspotify** [comment]
Thanks, that's great :) I already backported it to our local fork of the Android version, as we've had to do package renaming because of the name conflicts.

**Comment by szpak** [comment]
Great. Please let me know if you encounter any more issue with caching.
